/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_arvin_androidart_jni_NdkTest */

#ifndef _Included_net_arvin_androidart_jni_NdkTest
#define _Included_net_arvin_androidart_jni_NdkTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_arvin_androidart_jni_NdkTest
 * Method:    getSomethingFromNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_arvin_androidart_jni_NdkTest_getSomethingFromNDK
  (JNIEnv *, jclass);

/*
 * Class:     net_arvin_androidart_jni_NdkTest
 * Method:    reduce
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_arvin_androidart_jni_NdkTest_reduce
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
